CREATE DATABASE PROJECT;
SELECT * FROM PROJ;
DESC PROJ;

SELECT COUNT(*) FROM PROJ;

#TOTAL MANUFACTURED QUANTITY
SELECT CONCAT(ROUND(SUM(`Manufactured Qty`) / 1000000, 2), ' M') AS TOTAL_MANUFACTURED_QTY FROM PROJ;

#TOTAL REJECTED QUANTITY
SELECT CONCAT(ROUND(SUM(`REJECTED QTY`) / 1000000, 2), ' M') AS TOTAL_REJECTED_QTY FROM PROJ;

#TOTAL PROCESSED QUANTITY
SELECT CONCAT(ROUND(SUM(`PROCESSED QTY`) / 1000000, 2), ' M') AS TOTAL_PROCESSED_QTY FROM PROJ;

#TOTAL WASTAGE QUANTITY
SELECT  ROUND(SUM(`WASTAGE QTY`)) AS TOTAL_WASTAGE_QTY FROM PROJ;

#MACHINEWISE REJECTED QUANTITY
SELECT `MACHINE NAME` AS MACHINE_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM PROJ GROUP BY `MACHINE NAME`;

#EMPLOYEEWISE REJECTED QUANTITY
SELECT `EMP NAME` AS EMPLOYEE_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM PROJ GROUP BY `EMP NAME`;

#DEPARTMENTWISE REJECTED QUANTITY
SELECT `DEPARTMENT NAME` AS EMPLOYEE_NAME , SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY FROM PROJ GROUP BY `DEPARTMENT NAME`;

#MANUFACTURED VS REJECTED
SELECT  SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY, SUM(`MANUFACTURED QTY`) AS TOTAL_MANUFACTURED_QTY FROM PROJ;

#PRODUCTION COMPARISON TREND
SELECT `DOC DATE`,SUM(`MANUFACTURED QTY`) as TOTAL_MANUFACTURED_QTY, SUM(`REJECTED QTY`) AS TOTAL_REJECTED_QTY,SUM(`PROCESSED QTY`) AS TOTAL_PROCESSED_QTY FROM PROJ GROUP BY `DOC DATE`;




